[package]
name = "sb_compiler_parse_cst"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
copager = { workspace = true, features = ["derive", "tree"] }

[dev-dependencies]
copager = { workspace = true, features = ["derive", "template", "lalr1"] }
