[package]
name = "sb_compiler_analyze"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
sb_compiler_parse_ast = { path = "../parse_ast" }
