[workspace]
resolver = "2"
members = [
    "./compiler",
]

[workspace.dependencies]
anyhow = "1.0.93"
thiserror = "2.0.3"
copager = { git = "https://github.com/Tsukuba-Programming-Lab/Copager", rev = "fdce90d13b5ca3103b7ce9851f3c2982754438f9" }
