[package]
name = "sb_compiler_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
sb_compiler_lirgen_ir = { path = "../lirgen_ir" }
