[package]
name = "sb_compiler_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
sb_compiler_lirgen_ir = { path = "../lirgen_ir" }
sb_compiler_codegen_asm = { path = "../codegen_asm" }

[dev-dependencies]
sb_compiler_parse = { path = "../parse" }
sb_compiler_lirgen = { path = "../lirgen" }
