[package]
name = "sb_compiler_semcheck_hir"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { workspace = true }
sb_compiler_parse_ast = { path = "../parse_ast" }
sb_compiler_parse_cst = { path = "../parse_cst" }
sb_compiler_semcheck_async = { path = "../semcheck_async" }
sb_compiler_semcheck_impl = {  path = "../semcheck_impl" }
sb_compiler_semcheck_impl_var = { path = "../semcheck_impl_var" }
sb_compiler_semcheck_impl_typedecl = { path = "../semcheck_impl_typedecl" }
sb_compiler_type = { path = "../type" }
sb_compiler_utils = { path = "../utils" }
