[package]
name = "sb_compiler_semcheck_impl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
sb_compiler_semcheck_impl_vardecl = { path = "../semcheck_impl_vardecl" }
sb_compiler_semcheck_impl_type_decl = { path = "../semcheck_impl_type_decl" }
