[package]
name = "sb_compiler_lirgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
string-interner = { workspace = true }
sb_compiler_parse_cst = { path = "../parse_cst" }
sb_compiler_semcheck_hir = { path = "../semcheck_hir" }
sb_compiler_lirgen_ir = { path = "../lirgen_ir" }
sb_compiler_utils = { path = "../utils" }

[dev-dependencies]
sb_compiler_parse = { path = "../parse" }
sb_compiler_semcheck = { path = "../semcheck" }
