[package]
name = "sb_compiler_parse_ast"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
sb_compiler_parse_syntax = { path = "../parse_syntax" }
